copyright: Copyright &copy; 2024 Daniel Bodky
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: index.md
  - Setup:
      - setup/index.md
      - Installing Docker: setup/docker.md
      - Installing kubectl: setup/kubectl.md
      - Installing Educates: setup/educates.md
      - Creating an Educates Cluster: setup/create-cluster.md
  - About Educates:
      - about/index.md
      - Educates Components: about/components.md
      - Educates CRDs: about/crds.md
      - Educates Workflow: about/workflow.md
  - Creating Workshops:
      - authoring/index.md
      - Getting Started: authoring/basics.md
      - "Exploring a Workshop Session...": authoring/explore.md
      - Startup and Interactivity: authoring/startup-interactivity.md
      - Live-Editing Workshops: authoring/live-edit.md
plugins:
  - glightbox
repo_name: mocdaniel/educates-primer
repo_url: https://github.com/mocdaniel/educates-primer
site_name: Building Workshops with Educates
site_url: https://educates101.dbodky.me
theme:
  favicon: assets/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  icon:
    repo: fontawesome/brands/github
  logo: assets/nws.svg
  name: material
  palette:
    primary: deep orange
